<?php

namespace Webservice\MainBundle\Repository;
use Doctrine\Common\Collections\Criteria;

/**
 * SeanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeanceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSeanceNotFree()
    {
        $qb = $this ->createQueryBuilder('s');

        $qb ->where('s.price != 0');
        $resultat =$qb->getQuery() ;

        return $resultat->getResult();
    }

    public function findSeanceDate($date) {
        $qb = $this->createQueryBuilder("s");

        $qb->where('s.start_Seance = :date');
        $qb->setParameter('date', $date, \Doctrine\DBAL\Types\Type::DATETIME);

        $result = $qb->getQuery();

        return $result->getResult();
    }

    // TODO implement query builder
    public function findSeanceByFilmGenre($genre) {
        $qb = $this->createQueryBuilder('s');
        $resultat = $qb->getQuery();
        $resultat = $resultat->getResult();
        $listSeance = array();
        foreach ($resultat as $rs) {
            $film = $rs->getIdFilm();

            if ($film->getCategory() == $genre) {
                $listSeance[] =$rs;
            }
        }

        return $listSeance;
//        SELECT * FROM `seance`as s inner join film as f ON s.id_film = f.id WHERE f.category = "science-fiction"
    }
}
