site:
    resource: "@SiteBundle/Controller/"
    type:     annotation
    prefix:   /

webservice_services:
    resource: "@WebserviceServicesBundle/Resources/config/routing.yml"
    prefix:   /

webservice_dys:
    resource: "@WebserviceMainBundle/Resources/config/routing.yml"
    prefix:   /

site_user_connexion:
    path: /connexion
    defaults: { _controller: "@SiteBundle:Default:connexion" }
    requirements:
        _method: GET

